/*
Brainstormers 2D (Soccer Simulation League 2D)
PUBLIC SOURCE CODE RELEASE 2005
Copyright (C) 1998-2005 Neuroinformatics Group,
                        University of Osnabrueck, Germany

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
*/

#define yy_create_buffer si_create_buffer
#define yy_delete_buffer si_delete_buffer
#define yy_scan_buffer si_scan_buffer
#define yy_scan_string si_scan_string
#define yy_scan_bytes si_scan_bytes
#define yy_flex_debug si_flex_debug
#define yy_init_buffer si_init_buffer
#define yy_flush_buffer si_flush_buffer
#define yy_load_buffer_state si_load_buffer_state
#define yy_switch_to_buffer si_switch_to_buffer
#define yyin siin
#define yyleng sileng
#define yylex silex
#define yyout siout
#define yyrestart sirestart
#define yytext sitext
#define yywrap siwrap

/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /net/leela/export/stu_home/gruppen/soccer/Repository/robocup/bs2k/omnibot/lex.si.c,v 1.4 2004/07/28 11:59:00 tgabel Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 133
#define YY_END_OF_BUFFER 134
static yyconst short int yy_accept[502] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
      134,  132,    1,  129,  130,  132,  131,  132,  132,  132,
      132,  132,  132,  132,  132,  132,  132,  132,  132,  132,
      132,   70,   66,  133,   71,   70,   69,   70,   70,    1,
       73,   95,   97,   98,  133,   96,   99,  100,  133,  115,
      133,  133,  133,  133,  133,  133,  133,  133,  133,  120,
      123,  133,  133,   32,   34,   35,  133,   33,   36,   42,

       39,   40,   38,   41,   37,   55,   64,  133,   63,   60,
       58,   62,   56,   61,   57,   59,   43,   47,   46,  133,
       44,  133,   48,   49,   50,   51,   54,  133,   52,    3,
        5,    6,  133,    4,    7,   19,  133,  133,  133,  133,
      133,  133,  133,  133,  133,   25,  133,   26,   27,   30,
      133,   28,    1,   21,   22,   24,  133,   23,  116,  117,
      133,  118,  125,  133,  128,  126,  127,    1,  131,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,   70,   66,   69,   70,   70,    1,   96,
      115,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,   32,   33,   36,   55,
       63,   43,   44,    0,   48,   50,   52,   53,   52,    0,
        3,    4,    7,    0,    0,   16,    0,    0,    0,    0,
       17,    0,    0,    0,   25,   26,   27,   28,   29,   28,
        0,    1,   22,   23,  116,  118,  118,  118,    0,  125,
      128,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,   31,    0,    0,   70,   70,    0,    0,
        0,    0,  103,    0,    0,  113,    0,    0,    0,    0,
        0,    0,    0,    0,   53,    0,   53,    0,    0,   10,
        0,    0,    0,    0,    0,    0,   29,    0,   29,  118,

        0,  118,    0,    0,    0,    0,    0,    0,   65,  124,
        0,    0,    0,    0,    0,    0,   70,   67,  111,    0,
      102,  110,    0,    0,    0,    0,  112,    0,  106,    0,
        0,    0,   18,    9,    0,    0,    0,    0,    0,   13,
        0,    0,    0,  119,    0,    0,    0,    0,    0,    0,
        0,    0,    0,   70,    0,    0,    0,  108,    0,    0,
        0,    0,    0,    0,    0,    0,   14,   15,    8,    0,
        0,    0,    0,    0,   87,   88,    0,    0,    0,    0,
        0,    0,    0,    0,   70,    0,  104,  105,    0,    0,
        0,    0,    0,   45,   11,   12,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,   76,    0,    0,   68,
        0,  107,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    2,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   89,    0,    0,    0,   79,
       80,    0,   90,   91,    0,   75,    0,  114,  101,    0,
        0,    0,    0,    0,    0,    0,   77,   78,   94,  109,
        0,    0,    0,    0,   81,   82,   85,   86,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   83,   84,    0,
        0,    0,    0,    0,    0,    0,   74,    0,    0,  121,
        0,    0,    0,    0,    0,    0,   92,   93,    0,  122,

        0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    4,    1,    1,    1,    1,    1,    5,
        6,    1,    7,    1,    7,    8,    1,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    1,    1,    1,
        1,    1,    1,    1,   11,   12,   13,   14,   15,   16,
       17,   18,   19,    1,   20,   21,   22,   23,   24,   25,
        1,   26,   27,   28,   29,   30,   31,    1,   32,    1,
        1,    1,    1,    1,   10,    1,   11,   12,   13,   14,

       15,   16,   17,   18,   19,    1,   20,   21,   22,   23,
       24,   25,    1,   26,   27,   28,   29,   30,   31,    1,
       32,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[33] =
    {   0,
        1,    2,    2,    3,    2,    2,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1
    } ;

static yyconst short int yy_base[507] =
    {   0,
        0,    0,   31,   57,   33,   39,   83,   91,   99,    0,
       42,   48,  129,  137,  145,    0,  169,    0,  196,  212,
      612,  611,  228,  236,  244,  252,  260,    0,   40,   44,
       63,   72,   50,   74,  105,  146,  158,  178,  290,  315,
      614,  617,  611,  617,  617,  603,  602,  595,  585,  582,
      581,  580,  581,  589,  580,  583,  587,  584,  578,  583,
      578,    0,  594,  617,  617,  586,  585,  578,  577,  589,
      617,  617,  617,  617,  581,  580,  617,  617,  579,  578,
      575,   67,  566,  560,   44,   93,  554,  563,  562,  617,
      617,  559,  556,  576,  617,  617,  568,  567,  573,  617,

      617,  617,  617,  617,  617,  572,  617,  564,  563,  617,
      617,  617,  617,  617,  617,  617,  569,  617,  617,  561,
      560,  544,    0,  617,  565,  617,  617,  557,   94,  563,
      617,  617,  555,  554,  560,  617,  550,  541,   63,   99,
      537,  548,  544,  534,  536,  552,  544,  543,  549,  617,
      541,  164,  547,  617,  546,  617,  538,  537,  543,  617,
      535,  184,  541,  533,  532,  617,  617,  538,  530,  522,
      511,  512,  509,  519,  522,  521,  512,  517,  504,  512,
      516,   76,  504,    0,  523,  515,  507,  501,  519,  511,
      510,  491,  506,  499,  502,  483,  487,  486,  479,  495,

      498,  482,  492,  492,  484,  484,  501,  493,  499,  498,
      490,  496,  488,  485,    0,  493,  200,  136,  202,  147,
      492,  484,  490,  470,  473,  617,  458,  462,  461,  462,
      617,  461,  460,  469,  480,  472,  478,  216,  154,  255,
      182,  477,  476,  468,  474,  259,  159,  267,  197,  473,
      465,  449,  449,  446,  446,  454,  447,  441,  438,  445,
      437,  436,  430,  617,  434,  445,  444,  442,  439,  442,
      437,  434,  617,  427,  430,  617,  436,  428,  426,  417,
      432,  431,  422,  423,  168,  434,  433,  420,  422,  617,
      413,  416,  423,  410,  421,  419,  192,  424,  423,  211,

      422,  421,  403,  413,  417,  400,  415,  105,  617,  617,
      414,  395,  403,  411,  405,  409,  392,    0,  617,  407,
      617,  617,  392,  404,  400,  394,  402,  401,  617,  393,
      385,  389,  617,  617,  383,  395,  390,  389,  388,  617,
      387,  375,  388,  617,  379,  202,  383,  109,  386,  382,
      371,  384,  369,  377,  380,  359,  368,  617,  365,  364,
      364,  374,  353,  368,  351,  360,  617,  617,  617,  370,
      369,  367,  358,  357,  617,  617,  365,  351,  357,  344,
      356,  347,  357,  338,  352,  343,  617,  617,  354,  349,
      339,  341,  338,  617,  617,  617,  340,  339,  337,  344,

      343,  339,  330,  323,  323,  327,  617,  311,  319,    0,
      316,  617,  319,  317,  320,  319,  309,  308,  305,  305,
      303,  310,  111,  310,  617,  206,  305,  292,  294,  294,
      298,  299,  297,  296,  295,  617,  297,  296,  277,  617,
      617,  218,  617,  617,  272,  617,  288,  617,  617,  278,
      277,  280,  278,  226,  234,  283,  617,  617,  617,  617,
      273,  272,  279,  270,  617,  617,  617,  617,  259,  251,
      249,  245,  258,  255,  245,  237,  224,  617,  617,  224,
      189,  173,  172,  148,  144,  135,  617,  120,  130,  617,
      104,  100,   85,   70,  267,   49,  617,  617,   21,  617,

      617,  341,  344,  347,  350,  353
    } ;

static yyconst short int yy_def[507] =
    {   0,
      501,    1,  502,  502,    1,    1,  503,  503,  503,    9,
      503,  503,  503,  503,  503,   15,  503,   17,  503,  503,
      504,  504,  503,  503,  503,  503,  503,   27,  503,  503,
      503,  503,    1,    1,  503,  503,  503,  503,  503,  503,
      501,  501,  501,  501,  501,  501,  501,  501,  501,  501,
      501,  501,  501,  501,  501,  501,  501,  501,  501,  501,
      501,  505,  501,  501,  501,  505,  505,  505,  505,  501,
      501,  501,  501,  501,  501,  501,  501,  501,  501,  501,
      501,  501,  501,  501,  501,  501,  501,  501,  501,  501,
      501,  501,  501,  501,  501,  501,  501,  501,  501,  501,

      501,  501,  501,  501,  501,  501,  501,  501,  501,  501,
      501,  501,  501,  501,  501,  501,  501,  501,  501,  501,
      501,  501,  506,  501,  501,  501,  501,  501,  501,  501,
      501,  501,  501,  501,  501,  501,  501,  501,  501,  501,
      501,  501,  501,  501,  501,  501,  501,  501,  501,  501,
      501,  501,  501,  501,  501,  501,  501,  501,  501,  501,
      501,  501,  501,  501,  501,  501,  501,  501,  501,  501,
      501,  501,  501,  501,  501,  501,  501,  501,  501,  501,
      501,  501,  501,  505,  501,  505,  505,  505,  501,  501,
      501,  501,  501,  501,  501,  501,  501,  501,  501,  501,

      501,  501,  501,  501,  501,  501,  501,  501,  501,  501,
      501,  501,  501,  501,  506,  501,  501,  501,  501,  501,
      501,  501,  501,  501,  501,  501,  501,  501,  501,  501,
      501,  501,  501,  501,  501,  501,  501,  501,  501,  501,
      501,  501,  501,  501,  501,  501,  501,  501,  501,  501,
      501,  501,  501,  501,  501,  501,  501,  501,  501,  501,
      501,  501,  501,  501,  501,  501,  505,  505,  501,  501,
      501,  501,  501,  501,  501,  501,  501,  501,  501,  501,
      501,  501,  501,  501,  501,  501,  501,  501,  501,  501,
      501,  501,  501,  501,  501,  501,  501,  501,  501,  501,

      501,  501,  501,  501,  501,  501,  501,  501,  501,  501,
      501,  501,  501,  501,  501,  501,  505,  505,  501,  501,
      501,  501,  501,  501,  501,  501,  501,  501,  501,  501,
      501,  501,  501,  501,  501,  501,  501,  501,  501,  501,
      501,  501,  501,  501,  501,  501,  501,  501,  501,  501,
      501,  501,  501,  505,  501,  501,  501,  501,  501,  501,
      501,  501,  501,  501,  501,  501,  501,  501,  501,  501,
      501,  501,  501,  501,  501,  501,  501,  501,  501,  501,
      501,  501,  501,  501,  505,  501,  501,  501,  501,  501,
      501,  501,  501,  501,  501,  501,  501,  501,  501,  501,

      501,  501,  501,  501,  501,  501,  501,  501,  501,  505,
      501,  501,  501,  501,  501,  501,  501,  501,  501,  501,
      501,  501,  501,  501,  501,  501,  501,  501,  501,  501,
      501,  501,  501,  501,  501,  501,  501,  501,  501,  501,
      501,  501,  501,  501,  501,  501,  501,  501,  501,  501,
      501,  501,  501,  501,  501,  501,  501,  501,  501,  501,
      501,  501,  501,  501,  501,  501,  501,  501,  501,  501,
      501,  501,  501,  501,  501,  501,  501,  501,  501,  501,
      501,  501,  501,  501,  501,  501,  501,  501,  501,  501,
      501,  501,  501,  501,  501,  501,  501,  501,  501,  501,

        0,  501,  501,  501,  501,  501
    } ;

static yyconst short int yy_nxt[650] =
    {   0,
       42,   43,   42,   42,   44,   45,   46,   42,   47,   42,
       42,   48,   49,   50,   51,   52,   53,   54,   55,   56,
       42,   57,   42,   58,   59,   42,   60,   61,   42,   42,
       42,   42,   63,   64,   70,   64,   65,   66,   71,   67,
       70,  146,  500,   90,   71,  146,  147,   91,  148,   90,
      147,  153,  148,   91,  197,  154,   68,   69,   63,   64,
       92,   64,   65,   66,  149,   67,   92,  198,  150,  151,
       93,  152,  226,  149,  499,  153,   93,  150,  151,  154,
      152,  193,   68,   69,   72,  194,  227,   73,   74,   75,
      264,   76,   72,  496,  495,   73,   74,   75,  265,   76,

       77,  218,  219,  199,   78,   79,  155,   80,  220,  228,
      156,  157,   81,  158,  346,  494,   82,  200,   83,   84,
      201,   85,  229,  347,  493,   86,   87,  378,   88,   89,
       94,  440,  379,   95,   96,   97,  441,   98,   94,  492,
      491,   95,   96,   97,  285,   98,   99,  155,  490,  100,
      220,  156,  157,  286,  158,  287,  101,  489,  488,  159,
      102,  103,  297,  160,  161,  104,  162,  300,  241,  105,
      106,  239,  240,  249,  107,  108,  285,  109,  241,  159,
      110,  111,  220,  160,  161,  112,  162,  487,  298,  113,
      299,  247,  248,  114,  115,  486,  116,  117,  249,  118,

      297,  119,  120,  301,  121,  302,  241,  218,  219,  218,
      219,  485,  122,  117,  220,  118,  220,  119,  120,  300,
      121,  374,  375,  239,  240,  249,  443,  376,  122,  125,
      241,  444,  126,  127,  128,  484,  129,  125,  457,  483,
      126,  127,  128,  458,  129,  130,  465,  482,  131,  132,
      133,  466,  134,  130,  467,  481,  131,  132,  133,  468,
      134,  135,  239,  240,  480,  136,  247,  248,  477,  241,
      476,  137,  475,  249,  247,  248,  474,  138,  478,  473,
      139,  249,  140,  479,  141,  142,  143,  497,  472,  144,
      145,  163,  498,  471,  470,  469,  164,  464,  165,  463,

      462,  461,  460,  459,  456,  455,  454,  453,  452,  451,
      166,  450,  449,  448,  447,  167,  163,  446,  445,  442,
      439,  164,  438,  165,  437,  436,  435,  434,  433,  432,
      431,  430,  429,  428,  427,  166,  426,  425,  424,  423,
      167,   62,   62,   62,   64,   64,   64,  123,  123,  123,
      184,  422,  184,  215,  215,  421,  420,  419,  418,  417,
      416,  415,  414,  413,  412,  411,  410,  409,  408,  407,
      406,  405,  404,  403,  402,  401,  400,  399,  398,  397,
      396,  395,  394,  393,  392,  391,  390,  389,  388,  387,
      386,  385,  384,  383,  382,  381,  380,  377,  373,  372,

      371,  370,  369,  368,  367,  366,  365,  364,  363,  362,
      361,  360,  359,  358,  357,  356,  355,  354,  353,  352,
      351,  350,  349,  348,  345,  344,  343,  342,  341,  302,
      302,  299,  299,  340,  339,  338,  337,  336,  335,  334,
      333,  287,  287,  332,  331,  330,  329,  328,  327,  326,
      325,  324,  323,  322,  321,  320,  319,  318,  317,  316,
      315,  314,  313,  312,  311,  310,  309,  308,  307,  306,
      305,  304,  303,  251,  250,  245,  244,  243,  242,  237,
      236,  235,  296,  295,  294,  293,  292,  291,  290,  289,
      288,  223,  222,  221,  216,  284,  213,  212,  211,  210,

      209,  208,  207,  283,  282,  281,  280,  279,  278,  277,
      276,  275,  274,  273,  272,  271,  270,  269,  191,  190,
      189,  268,  267,  186,  185,  266,  263,  262,  261,  260,
      259,  258,  257,  256,  255,  254,  253,  252,  169,  168,
      251,  251,  250,  246,  245,  244,  244,  243,  242,  238,
      237,  236,  236,  235,  234,  233,  232,  231,  230,  225,
      224,  223,  222,  222,  221,  217,  216,  214,  213,  213,
      212,  211,  211,  210,  209,  208,  208,  207,  206,  205,
      204,  203,  202,  196,  195,  192,  191,  191,  190,  190,
      189,  188,  187,  186,  186,  185,  183,  182,  181,  180,

      179,  178,  177,  176,  175,  174,  173,  172,  171,  170,
      169,  169,  168,  501,  124,  124,   41,  501,  501,  501,
      501,  501,  501,  501,  501,  501,  501,  501,  501,  501,
      501,  501,  501,  501,  501,  501,  501,  501,  501,  501,
      501,  501,  501,  501,  501,  501,  501,  501,  501
    } ;

static yyconst short int yy_chk[650] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    3,    3,    5,    3,    3,    3,    5,    3,
        6,   29,  499,   11,    6,   30,   29,   11,   29,   12,
       30,   33,   30,   12,   85,   33,    3,    3,    4,    4,
       11,    4,    4,    4,   31,    4,   12,   85,   31,   31,
       11,   31,  139,   32,  496,   34,   12,   32,   32,   34,
       32,   82,    4,    4,    7,   82,  139,    7,    7,    7,
      182,    7,    8,  494,  493,    8,    8,    8,  182,    8,

        9,  129,  129,   86,    9,    9,   35,    9,  129,  140,
       35,   35,    9,   35,  308,  492,    9,   86,    9,    9,
       86,    9,  140,  308,  491,    9,    9,  348,    9,    9,
       13,  423,  348,   13,   13,   13,  423,   13,   14,  489,
      488,   14,   14,   14,  218,   14,   15,   36,  486,   15,
      218,   36,   36,  220,   36,  220,   15,  485,  484,   37,
       15,   15,  239,   37,   37,   15,   37,  247,  239,   15,
       17,  152,  152,  247,   17,   17,  285,   17,  152,   38,
       17,   17,  285,   38,   38,   17,   38,  483,  241,   17,
      241,  162,  162,   17,   17,  482,   17,   19,  162,   19,

      297,   19,   19,  249,   19,  249,  297,  217,  217,  219,
      219,  481,   19,   20,  217,   20,  219,   20,   20,  300,
       20,  346,  346,  238,  238,  300,  426,  346,   20,   23,
      238,  426,   23,   23,   23,  480,   23,   24,  442,  477,
       24,   24,   24,  442,   24,   25,  454,  476,   25,   25,
       25,  454,   25,   26,  455,  475,   26,   26,   26,  455,
       26,   27,  240,  240,  474,   27,  246,  246,  472,  240,
      471,   27,  470,  246,  248,  248,  469,   27,  473,  464,
       27,  248,   27,  473,   27,   27,   27,  495,  463,   27,
       27,   39,  495,  462,  461,  456,   39,  453,   39,  452,

      451,  450,  447,  445,  439,  438,  437,  435,  434,  433,
       39,  432,  431,  430,  429,   39,   40,  428,  427,  424,
      422,   40,  421,   40,  420,  419,  418,  417,  416,  415,
      414,  413,  411,  409,  408,   40,  406,  405,  404,  403,
       40,  502,  502,  502,  503,  503,  503,  504,  504,  504,
      505,  402,  505,  506,  506,  401,  400,  399,  398,  397,
      393,  392,  391,  390,  389,  386,  385,  384,  383,  382,
      381,  380,  379,  378,  377,  374,  373,  372,  371,  370,
      366,  365,  364,  363,  362,  361,  360,  359,  357,  356,
      355,  354,  353,  352,  351,  350,  349,  347,  345,  343,

      342,  341,  339,  338,  337,  336,  335,  332,  331,  330,
      328,  327,  326,  325,  324,  323,  320,  317,  316,  315,
      314,  313,  312,  311,  307,  306,  305,  304,  303,  302,
      301,  299,  298,  296,  295,  294,  293,  292,  291,  289,
      288,  287,  286,  284,  283,  282,  281,  280,  279,  278,
      277,  275,  274,  272,  271,  270,  269,  268,  267,  266,
      265,  263,  262,  261,  260,  259,  258,  257,  256,  255,
      254,  253,  252,  251,  250,  245,  244,  243,  242,  237,
      236,  235,  234,  233,  232,  230,  229,  228,  227,  225,
      224,  223,  222,  221,  216,  214,  213,  212,  211,  210,

      209,  208,  207,  206,  205,  204,  203,  202,  201,  200,
      199,  198,  197,  196,  195,  194,  193,  192,  191,  190,
      189,  188,  187,  186,  185,  183,  181,  180,  179,  178,
      177,  176,  175,  174,  173,  172,  171,  170,  169,  168,
      165,  164,  163,  161,  159,  158,  157,  155,  153,  151,
      149,  148,  147,  146,  145,  144,  143,  142,  141,  138,
      137,  135,  134,  133,  130,  128,  125,  122,  121,  120,
      117,  109,  108,  106,   99,   98,   97,   94,   93,   92,
       89,   88,   87,   84,   83,   81,   80,   79,   76,   75,
       70,   69,   68,   67,   66,   63,   61,   60,   59,   58,

       57,   56,   55,   54,   53,   52,   51,   50,   49,   48,
       47,   46,   43,   41,   22,   21,  501,  501,  501,  501,
      501,  501,  501,  501,  501,  501,  501,  501,  501,  501,
      501,  501,  501,  501,  501,  501,  501,  501,  501,  501,
      501,  501,  501,  501,  501,  501,  501,  501,  501
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "sensor_lexer.lex"
#define INITIAL 0
#line 2 "sensor_lexer.lex"

  //#include "yy.tab.h"

#define siwrap() 1 /* we use the si-prefix instead of the standard yy. */
#undef YY_MAIN
/* we need a case-insensitive lexer, because the server gives sensor information in upper case if an object is very close to the player (i.e. he senses it) */
/* Following are the state definitions for the lexer.
*/
#define HEAR_MODE 1
 
#define HEAR_REFEREE 2

#define SENSE_MODE 3

#define SENSE_INFO 4

#define ERROR_MODE 5

#define SEE_MODE 6

#define SEE_OBJECT_MODE 7

#define SEE_OBJECT_ATTR 8

#define SEE_PLAYER 9

#define SEE_TEAMNAME 10

#define SEE_OBJECT_PARAMETER 11

#define MDP_MODE 12

#define MDP_OBJECT_MODE 13

#define MDP_PLAYER 14

#define MDP_OBJECT_PARAMETER 15

#define MDP_REFEREE 16

#define MDP_SCORE 17

#define SB_READ_DOUBLE 18

#define INIT_MODE 19

/* spaces are allowed in team names, but no quote marks*/
/* an INT ist also an DOUBLE, but not the other way */
#line 738 "lex.si.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 44 "sensor_lexer.lex"


#line 892 "lex.si.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 502 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 617 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 46 "sensor_lexer.lex"
/* ignore tabs and spaces*/ ;
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 49 "sensor_lexer.lex"
{ BEGIN MDP_MODE; return MDP;}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 51 "sensor_lexer.lex"
/* ignore tabs and spaces*/ ;
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 52 "sensor_lexer.lex"
{silval.ival = atoi(sitext); return INT;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 53 "sensor_lexer.lex"
{BEGIN MDP_OBJECT_MODE; return OB;} 
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 54 "sensor_lexer.lex"
{BEGIN 0;return CB;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 56 "sensor_lexer.lex"
/* ignore tabs and spaces*/ ;
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 57 "sensor_lexer.lex"
{ return VIEW_MODE;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 58 "sensor_lexer.lex"
{ silval.ival= HIGH; return VIEW_QUALITY;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 59 "sensor_lexer.lex"
{ silval.ival= LOW; return VIEW_QUALITY; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 60 "sensor_lexer.lex"
{ silval.ival= NARROW; return VIEW_WIDTH;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 61 "sensor_lexer.lex"
{ silval.ival= NORMAL; return VIEW_WIDTH;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 62 "sensor_lexer.lex"
{ silval.ival= WIDE; return VIEW_WIDTH;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 63 "sensor_lexer.lex"
{BEGIN MDP_REFEREE;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 64 "sensor_lexer.lex"
{BEGIN MDP_SCORE; return SI_SCORE; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 65 "sensor_lexer.lex"
{BEGIN MDP_PLAYER; if (WM::my_side == left_SIDE) silval.ival= my_TEAM; else silval.ival= his_TEAM; return SIDE; } 
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 66 "sensor_lexer.lex"
{BEGIN MDP_PLAYER; if (WM::my_side == right_SIDE) silval.ival= my_TEAM; else silval.ival= his_TEAM; return SIDE; } 
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 67 "sensor_lexer.lex"
{ BEGIN MDP_OBJECT_PARAMETER; return BALL;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 68 "sensor_lexer.lex"
{BEGIN MDP_MODE; return CB;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 70 "sensor_lexer.lex"
/* ignore tabs and spaces*/ ;
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 71 "sensor_lexer.lex"
{BEGIN MDP_MODE; return CB;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 73 "sensor_lexer.lex"
/* ignore tabs and spaces*/ ;
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 74 "sensor_lexer.lex"
{silval.ival = atoi(sitext); return INT;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 75 "sensor_lexer.lex"
{BEGIN MDP_MODE; return CB;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 77 "sensor_lexer.lex"
/* ignore tabs and spaces*/ ;
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 78 "sensor_lexer.lex"
{BEGIN MDP_OBJECT_PARAMETER; silval.ival = atoi(sitext); return UNUM;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 80 "sensor_lexer.lex"
/* ignore tabs and spaces*/ ;
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 81 "sensor_lexer.lex"
{silval.dval = double(atoi(sitext)); return DOUBLE;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 82 "sensor_lexer.lex"
{silval.dval = atof(sitext); return DOUBLE;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 83 "sensor_lexer.lex"
{BEGIN MDP_MODE; return CB;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 85 "sensor_lexer.lex"
{BEGIN SEE_MODE; return SEE;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 87 "sensor_lexer.lex"
/* ignore tabs and spaces*/ ;
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 88 "sensor_lexer.lex"
{silval.ival = atoi(sitext); return INT;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 89 "sensor_lexer.lex"
{BEGIN SEE_OBJECT_MODE; return OB;} 
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 90 "sensor_lexer.lex"
{BEGIN 0;return CB;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 92 "sensor_lexer.lex"
/* ignore tabs and spaces*/ ;
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 93 "sensor_lexer.lex"
{BEGIN SEE_PLAYER; return PLAYER;} /* player (ver. 6.00) */
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 94 "sensor_lexer.lex"
{BEGIN SEE_OBJECT_ATTR; return GOAL;} /* goal (ver. 6.00) */
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 95 "sensor_lexer.lex"
{BEGIN SEE_OBJECT_ATTR; return BALL;} /* ball (ver. 6.00) */
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 96 "sensor_lexer.lex"
{BEGIN SEE_OBJECT_ATTR; return FLAG;} /* flag (ver. 6.00) */
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 97 "sensor_lexer.lex"
{BEGIN SEE_OBJECT_ATTR; return LINE;} /* line (ver. 6.00) */
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 98 "sensor_lexer.lex"
{ return OB;} 
	YY_BREAK
/*<SEE_OBJECT_MODE>{CLOSING_BRACKET} {BEGIN SEE_OBJECT_PARAMETER; return CB;}*/
case 43:
YY_RULE_SETUP
#line 101 "sensor_lexer.lex"
/* ignore tabs and spaces*/ ;
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 102 "sensor_lexer.lex"
{silval.ival = atoi(sitext); return UNUM;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 103 "sensor_lexer.lex"
{return GOALIE;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 104 "sensor_lexer.lex"
{BEGIN SEE_OBJECT_PARAMETER; return CB;}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 105 "sensor_lexer.lex"
{BEGIN SEE_TEAMNAME;} 
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 106 "sensor_lexer.lex"
{
 if (strcmp( WM::my_team_name, sitext) == 0 )
   silval.ival= my_TEAM;
 else
   silval.ival= his_TEAM;
 //cout << "\nWM::my_team_name= [" << WM::my_team_name << "] arg3= [" << sitext << "]  (pteam == MY_TEAM)= " << (strcmp( WM::my_team_name, sitext) == 0);
 return WHICHTEAM;
}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 114 "sensor_lexer.lex"
{BEGIN SEE_PLAYER;}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 116 "sensor_lexer.lex"
/* ignore tabs and spaces*/ ;
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 117 "sensor_lexer.lex"
{;return OB;} 
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 118 "sensor_lexer.lex"
{silval.dval = double(atoi(sitext)); return DOUBLE;}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 119 "sensor_lexer.lex"
{silval.dval = atof(sitext); return DOUBLE;}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 120 "sensor_lexer.lex"
{BEGIN SEE_MODE; return CB;}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 122 "sensor_lexer.lex"
/* ignore tabs and spaces*/ ;
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 123 "sensor_lexer.lex"
{return _L_;}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 124 "sensor_lexer.lex"
{return _R_;}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 125 "sensor_lexer.lex"
{return _C_;}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 126 "sensor_lexer.lex"
{return _T_;}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 127 "sensor_lexer.lex"
{return _B_;}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 128 "sensor_lexer.lex"
{return _P_;}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 129 "sensor_lexer.lex"
{return _G_;}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 130 "sensor_lexer.lex"
{silval.ival = atoi(sitext); return INT;}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 131 "sensor_lexer.lex"
{BEGIN SEE_OBJECT_PARAMETER; return CB;}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 134 "sensor_lexer.lex"
{ BEGIN HEAR_MODE; return HEAR;}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 136 "sensor_lexer.lex"
/* ignore tabs and spaces*/ ;
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 137 "sensor_lexer.lex"
{return SELF;}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 138 "sensor_lexer.lex"
{BEGIN HEAR_REFEREE; return REFEREE;}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 139 "sensor_lexer.lex"
{silval.ival = atoi(sitext); return INT;}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 140 "sensor_lexer.lex"
{ silval.sval = 0;/*strdup(sitext)*/; return STRING;}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 141 "sensor_lexer.lex"
{BEGIN 0; return CB;}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 143 "sensor_lexer.lex"
/* ignore tabs and spaces*/ ;
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 144 "sensor_lexer.lex"
{BEGIN 0; return CB; }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 146 "sensor_lexer.lex"
{ silval.ival= PM_before_kick_off; return PMODE;}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 147 "sensor_lexer.lex"
{ silval.ival= PM_time_over; return PMODE;}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 148 "sensor_lexer.lex"
{ silval.ival= PM_play_on; return PMODE;}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 149 "sensor_lexer.lex"
{ silval.ival= PM_kick_off_l; return PMODE;}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 150 "sensor_lexer.lex"
{ silval.ival= PM_kick_off_r; return PMODE;}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 151 "sensor_lexer.lex"
{ silval.ival= PM_kick_in_l; return PMODE;}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 152 "sensor_lexer.lex"
{ silval.ival= PM_kick_in_r; return PMODE;}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 153 "sensor_lexer.lex"
{ silval.ival= PM_free_kick_l; return PMODE;}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 154 "sensor_lexer.lex"
{ silval.ival= PM_free_kick_r; return PMODE;}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 155 "sensor_lexer.lex"
{ silval.ival= PM_corner_kick_l; return PMODE;}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 156 "sensor_lexer.lex"
{ silval.ival= PM_corner_kick_r; return PMODE;}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 157 "sensor_lexer.lex"
{ silval.ival= PM_goal_kick_l; return PMODE;}
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 158 "sensor_lexer.lex"
{ silval.ival= PM_goal_kick_r; return PMODE;}
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 159 "sensor_lexer.lex"
{ silval.ival= PM_goal_l; return PMODE;}
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 160 "sensor_lexer.lex"
{ silval.ival= PM_goal_r; return PMODE;}
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 161 "sensor_lexer.lex"
{ silval.ival= PM_drop_ball; return PMODE;}
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 162 "sensor_lexer.lex"
{ silval.ival= PM_offside_l; return PMODE;}
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 163 "sensor_lexer.lex"
{ silval.ival= PM_offside_r; return PMODE;}
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 164 "sensor_lexer.lex"
{ silval.ival= PM_goalie_catch_ball_l; return PMODE;}
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 165 "sensor_lexer.lex"
{ silval.ival= PM_goalie_catch_ball_r; return PMODE;}
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 168 "sensor_lexer.lex"
{BEGIN SENSE_MODE;  return SENSE_BODY ;}
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 170 "sensor_lexer.lex"
/* ignore tabs and spaces. */
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 171 "sensor_lexer.lex"
{silval.ival = atoi(sitext); return INT;}
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 172 "sensor_lexer.lex"
{BEGIN SENSE_INFO; return OB;}
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 173 "sensor_lexer.lex"
{BEGIN 0; return CB;}
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 175 "sensor_lexer.lex"
/* ignore tabs and spaces. */
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 176 "sensor_lexer.lex"
{BEGIN SENSE_MODE; return CB;}  
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 177 "sensor_lexer.lex"
{return VIEW_MODE;}
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 178 "sensor_lexer.lex"
{ silval.ival= HIGH; return VIEW_QUALITY;}
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 179 "sensor_lexer.lex"
{ silval.ival= LOW; return VIEW_QUALITY; }
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 180 "sensor_lexer.lex"
{ silval.ival= NARROW; return VIEW_WIDTH;}
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 181 "sensor_lexer.lex"
{ silval.ival= NORMAL; return VIEW_WIDTH;}
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 182 "sensor_lexer.lex"
{ silval.ival= WIDE; return VIEW_WIDTH;}
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 183 "sensor_lexer.lex"
{BEGIN SB_READ_DOUBLE; return STAMINA;}
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 184 "sensor_lexer.lex"
{BEGIN SB_READ_DOUBLE; return SPEED;}
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 185 "sensor_lexer.lex"
{BEGIN SB_READ_DOUBLE; return HEAD_ANGLE;}
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 186 "sensor_lexer.lex"
{return SI_KICK;}
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 187 "sensor_lexer.lex"
{return SI_DASH;}
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 188 "sensor_lexer.lex"
{return SI_TURN;}
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 189 "sensor_lexer.lex"
{return SI_SAY;}
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 190 "sensor_lexer.lex"
{return SI_TURN_NECK;}
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 191 "sensor_lexer.lex"
{silval.ival = atoi(sitext); return INT;}
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 193 "sensor_lexer.lex"
/* ignore tabs and spaces*/ ;
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 194 "sensor_lexer.lex"
{BEGIN SENSE_MODE; return CB;}  
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 195 "sensor_lexer.lex"
{silval.dval = atof(sitext); return DOUBLE;}
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 197 "sensor_lexer.lex"
{BEGIN ERROR_MODE; return SI_ERROR ;}
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 199 "sensor_lexer.lex"
/* ignore tabs and spaces. */
	YY_BREAK
case 121:
YY_RULE_SETUP
#line 200 "sensor_lexer.lex"
{return UNKNOWN_COMMAND;}
	YY_BREAK
case 122:
YY_RULE_SETUP
#line 201 "sensor_lexer.lex"
{return ILLEGAL_COMMAND_FORM;}
	YY_BREAK
case 123:
YY_RULE_SETUP
#line 202 "sensor_lexer.lex"
{BEGIN 0; return CB;}
	YY_BREAK
case 124:
YY_RULE_SETUP
#line 204 "sensor_lexer.lex"
{BEGIN INIT_MODE; return SI_INIT ;}
	YY_BREAK
case 125:
YY_RULE_SETUP
#line 206 "sensor_lexer.lex"
/* ignore tabs and spaces*/ ;
	YY_BREAK
case 126:
YY_RULE_SETUP
#line 207 "sensor_lexer.lex"
{silval.ival = left_SIDE; return SIDE;}
	YY_BREAK
case 127:
YY_RULE_SETUP
#line 208 "sensor_lexer.lex"
{silval.ival = right_SIDE; return SIDE;}
	YY_BREAK
case 128:
YY_RULE_SETUP
#line 209 "sensor_lexer.lex"
{BEGIN HEAR_REFEREE; silval.ival = atoi(sitext); return INT;}
	YY_BREAK
case 129:
YY_RULE_SETUP
#line 211 "sensor_lexer.lex"
{ return OB;} 
	YY_BREAK
case 130:
YY_RULE_SETUP
#line 212 "sensor_lexer.lex"
{ return CB;}
	YY_BREAK
case 131:
YY_RULE_SETUP
#line 213 "sensor_lexer.lex"
{silval.ival = atoi(sitext); return INT;}
	YY_BREAK
case 132:
YY_RULE_SETUP
#line 215 "sensor_lexer.lex"
; 
	YY_BREAK
case 133:
YY_RULE_SETUP
#line 216 "sensor_lexer.lex"
ECHO;
	YY_BREAK
#line 1648 "lex.si.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(HEAR_MODE):
case YY_STATE_EOF(HEAR_REFEREE):
case YY_STATE_EOF(SENSE_MODE):
case YY_STATE_EOF(SENSE_INFO):
case YY_STATE_EOF(ERROR_MODE):
case YY_STATE_EOF(SEE_MODE):
case YY_STATE_EOF(SEE_OBJECT_MODE):
case YY_STATE_EOF(SEE_OBJECT_ATTR):
case YY_STATE_EOF(SEE_PLAYER):
case YY_STATE_EOF(SEE_TEAMNAME):
case YY_STATE_EOF(SEE_OBJECT_PARAMETER):
case YY_STATE_EOF(MDP_MODE):
case YY_STATE_EOF(MDP_OBJECT_MODE):
case YY_STATE_EOF(MDP_PLAYER):
case YY_STATE_EOF(MDP_OBJECT_PARAMETER):
case YY_STATE_EOF(MDP_REFEREE):
case YY_STATE_EOF(MDP_SCORE):
case YY_STATE_EOF(SB_READ_DOUBLE):
case YY_STATE_EOF(INIT_MODE):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 502 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 502 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 501);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 216 "sensor_lexer.lex"



